server:
  port: 8080

spring:
  application:
    name: small_shop
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: test
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
      data-locations: classpath:db/data-h2.sql
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
