server:
  port: 8080

spring:
  application:
    name: small_shop
  datasource:
    url: jdbc:mysql://localhost:3306/small_shop?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
